{% set setup_data = load_setup_py_data() %}
package:
  name: track-duplicates
  version: {{ setup_data['version'] }}

source:
  git_rev: {{ setup_data['version'] }}
  git_url: https://github.com/genomewalker/track-duplicates.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python>=3.8,<3.10
    - setuptools>=18.0
    - pip
    - Cython>=0.29.24
  run:
    - python>=3.8,<3.10
    - pandas>=1.4.2
    - tqdm==4.50.0
    - pysam>=0.17.0
    - numpy>=1.21.2
    - biopython>=1.79
    
test:
  commands:
    - trackDups -h

about:
  home: https://github.com/genomewalker/track-duplicates
  summary: "A simple tool to extract damaged reads from BAM files"
  license: {{ setup_data['license'] }}
  license_file: LICENSE
